[changelog]
# template for the changelog header
header = """
# Changelog\n
All notable changes to this project will be documented in this file.\n
"""
# template for the changelog body
# https://keats.github.io/tera/docs/#introduction
body = """
---\n
{% if version %}\
  ## {{ version | trim_start_matches(pat="v") }} - {{ timestamp | date(format="%Y-%m-%d") }}
{% else %}\
  ## Unreleased
{% endif %}\
{% for group, commits in commits | group_by(attribute="group") %}
  ### {{ group | striptags | trim | upper_first }}
  {% raw %}\n{% endraw %}\
  {%- for commit in commits %}\
    {% if commit.remote.pr_title -%}
      {%- set commit_message = commit.remote.pr_title -%}
    {%- else -%}
      {%- set commit_message = commit.message -%}
    {%- endif -%}
    - {{ commit_message | split(pat="\n") | first | upper_first }}\
      {% if commit.remote.pr_number %} \
        ([#{{ commit.remote.pr_number }}]({{ self::remote_url() }}/pull/{{ commit.remote.pr_number }})) \
      {%- endif %}
    {% if commit.breaking -%}
      {% raw %}  {% endraw %}- **BREAKING**: {{commit.breaking_description}}
    {% endif -%}
  {% endfor -%}
{% endfor %}

{%- if github -%}
  {%- set contributors = github.contributors | filter(attribute="username") -%}
  {% if contributors | length != 0 %}
    ### 🧑‍🤝‍🧑 Contributors
    {% raw %}{% endraw %}\
  {%- endif %}\
  {% for contributor in contributors %}
    {% if contributor.username != 'dependabot[bot]' %}\
      * [@{{ contributor.username }}](https://github.com/{{ contributor.username }})
    {%- endif %}
  {%- endfor -%}
{%- endif -%}

{% if version %}
    {% if previous.version %}\
      **Full Changelog**: <{{ self::remote_url() }}/compare/{{ previous.version }}...{{ version }}>
    {% endif %}
{% else -%}
{% endif %}

{%- macro remote_url() -%}
  https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}
{%- endmacro -%}
"""
# template for the changelog footer
footer = """
<!-- generated by git-cliff -->
"""
# remove the leading and trailing s
trim = true
# postprocessors
postprocessors = []
# render body even when there are no releases to process
# render_always = true
# output file path
output = "CHANGELOG.md"

[git]
# parse the commits based on https://www.conventionalcommits.org
conventional_commits = false
# filter out the commits that are not conventional
filter_unconventional = false
# process each line of a commit as an individual commit
split_commits = false
# regex for preprocessing the commit messages
commit_preprocessors = [
    # Replace issue numbers
    # { pattern = '\((\w+\s)?#([0-9]+)\)', replace = "([#${2}](<REPO>/issues/${2}))"},
    # Check spelling of the commit with https://github.com/crate-ci/typos
    # If the spelling is incorrect, it will be automatically fixed.
    # { pattern = '.*', replace_command = 'typos --write-changes -' },
]
# regex for parsing and grouping commits
commit_parsers = [
    { field = "github.pr_labels", pattern = "breaking-change", group = "<!-- 0 --> 🏗️ Breaking changes" },
    { field = "github.pr_labels", pattern = "enhancement", group = "<!-- 1 --> 🚀 Features" },
    { field = "github.pr_labels", pattern = "bug", group = "<!-- 2 --> 🐛 Fixes" },
    { field = "github.pr_labels", pattern = "documentation", group = "<!-- 3 --> 📝 Documentation" },
    { field = "github.pr_labels", pattern = "dependencies", group = "<!-- 4 --> 🧪 Dependencies" },
    { field = "github.pr_labels", pattern = ".*", group = "<!-- 5 --> 🌀 Miscellaneous" },
]
# filter out the commits that are not matched by commit parsers
filter_commits = false
# sort the tags topologically
topo_order = false
# sort the commits inside sections by oldest/newest order
sort_commits = "newest"

[remote.github]
owner = "SunDoge"
repo = "dlpark"
token = ""
