from __future__ import annotations

from typing import Any

def read_image(filename: str) -> object: ...
def read_image_versioned(filename: str) -> object: ...
def write_image(filename: str, tensor: Any) -> None: ...
def write_image_versioned(filename: str, tensor: Any) -> None: ...
