from typing import Any


class CudaTensorF32:
    def __init__(self, tensor: Any) -> None: ...
    @property
    def device_id(self) -> int: ...
    @property
    def device_pointer(self) -> int: ...
    @property
    def length(self) -> int: ...
    def __dlpack_device__(self) -> tuple[int, int]: ...
    def __dlpack__(self, stream: Any = None, **kwargs: Any) -> object: ...
