[package]
name = "dlpark-metal-python"
version = "0.1.0"
edition = "2024"
publish = false

[workspace]

[lib]
name = "_core"
crate-type = ["cdylib"]

[dependencies]
dlpark = { path = "../..", default-features = false, features = ["metal", "pyo3"] }
pyo3 = { version = "0.29", features = ["extension-module", "abi3-py39"] }
