from typing import Any


class CudaTensor:
    @classmethod
    def from_dlpack(cls, tensor: Any) -> CudaTensor: ...
    @property
    def device_id(self) -> int: ...
    @property
    def device_pointer(self) -> int: ...
    @property
    def length(self) -> int: ...
    def __dlpack_device__(self) -> tuple[int, int]: ...
    def __dlpack__(self, stream: Any = None, **kwargs: Any) -> object: ...
