from typing import Any


class MetalTensor:
    def __init__(self, values: list[float], rows: int, columns: int) -> None: ...
    @property
    def metal_buffer(self) -> int: ...
    @property
    def contents_pointer(self) -> int: ...
    def __dlpack_device__(self) -> tuple[int, int]: ...
    def __dlpack__(self, stream: Any = None, **kwargs: Any) -> object: ...
