from typing import Any


class MetalTensor:
    @classmethod
    def empty(cls, shape: list[int], device_id: int = 0) -> MetalTensor: ...
    @classmethod
    def from_values(
        cls, values: list[float], rows: int, columns: int
    ) -> MetalTensor: ...
    @classmethod
    def from_dlpack(cls, tensor: Any) -> MetalTensor: ...
    @property
    def metal_buffer(self) -> int: ...
    @property
    def contents_pointer(self) -> int | None: ...
    @property
    def length(self) -> int: ...
    def __dlpack_device__(self) -> tuple[int, int]: ...
    def __dlpack__(self, stream: Any = None, **kwargs: Any) -> object: ...
