name: Conventional Commits

on:
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  check:
    name: Check commit messages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Check PR commits
        uses: cocogitto/cocogitto-action@v4
        with:
          command: check
          args: ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }}
